import DashboardMainLayout from "components/components/screens/layouts/DashboardMainLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="light" lang="en">
      <body className="bg-base-200">
        <DashboardMainLayout>{children}</DashboardMainLayout>
      </body>
    </html>
  );
}
